# ============================================================
# EXAMPLE: Place this file in the PRIVATE repo (mkdocs_test)
# at:  .github/workflows/trigger-deploy.yml
# ============================================================
#
# This workflow fires a repository_dispatch event to the
# public repo (mkdocs_remote_test) whenever you push to main,
# so GitHub Pages rebuilds automatically.
#
# REQUIRED: Add a secret called DISPATCH_TOKEN in mkdocs_test
# containing a PAT with "contents: read" permission on
# mkdocs_remote_test (or use the same PAT you created).

name: Trigger Docs Deploy

on:
  push:
    branches: [main]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy in public repo
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DISPATCH_TOKEN }}" \
            https://api.github.com/repos/andeewn/mkdocs_remote_test/dispatches \
            -d '{"event_type":"mkdocs-update"}'
